#!/usr/bin/env bash

# migueldeoleiros: August 2022
# Script to change bringhtness on laptop screens
# You may need to change the Backlightfile and MaxValue to match your device

set -euo pipefail

Backlightfile="/sys/class/backlight/intel_backlight/brightness"
CurrentValue=$(cat $Backlightfile)
MaxValue='6000'

usage(){
    echo "usage: "
    echo " "
    echo "Increase brightness"
    echo "brighten --up N"
    echo " "
    echo "Decrease brightness"
    echo "brighten --down N"
    echo " "
    echo "Set brightness to N"
    echo "brighten --set N"
    echo "brighten --set max"
    echo " "
    echo "Show current brightness"
    echo "brighten --status"
}

changeBrightness(){
    if [[ $ExpectedValue -le $MaxValue && $ExpectedValue -ge 0 ]]; then
        echo $ExpectedValue
        echo $ExpectedValue >$Backlightfile
    else
        echo "error: MaxValue"
    fi
}

if [[ $# -eq 0 ]]; then
    usage
else
    if [[ $1 == "--up" ]]; then
        ExpectedValue=$(($CurrentValue + $2))
        changeBrightness
    elif [[ $1 == "--dowm" ]]; then
        ExpectedValue=$(($CurrentValue - $2))
        changeBrightness
    elif [[ $1 == "--set" ]]; then
        if [[ $2 == "max" ]]; then
            ExpectedValue=$MaxValue
        else
            ExpectedValue=$2
        fi
        changeBrightness
    elif [[ $1 == "--status" ]]; then
        echo $CurrentValue
    else
        usage
    fi 
fi

